export {
  resolveProjectRoot,
  resolvePythonCommand,
  resolvePythonSpawnArgs,
  shouldEnableAutoUpdates,
  resolveBackendHealthTimeoutMs,
  shouldOpenWindowBeforeBackend,
  isOllamaLaunchSkippable,
  CHROME_USER_AGENT,
  isHttpUrl,
  shouldOpenInSystemBrowser,
  shouldOpenAuthInSystemBrowser,
  COREX_OLLAMA_PORT,
  parseWindowsListeningPid,
  killPidTreeSync,
  killCoreXOllamaSync,
  killCoreXRuntimeSync,
  collectDescendantPids,
  parseWmicProcessRows,
  killZombieLlamaServersSync,
  preferIntegratedGpuForUi,
} from '../../../electronBootstrap.cjs';

export type {
  PathJoin,
  ExistsSync,
  ResolveProjectRootOptions,
  ResolvePythonCommandOptions,
  ResolvePythonSpawnArgsOptions,
  ShouldEnableAutoUpdatesOptions,
  ResolveBackendHealthTimeoutMsOptions,
} from './electronBootstrapTypes';
